#!/usr/bin/env python3
"""
Simple script to describe the generated plots.
"""

from pathlib import Path

def describe_plots():
    """Describe the plots generated by sangerqc --plots."""

    print("=" * 70)
    print("SANGER QC & TRIM - PLOT DESCRIPTIONS")
    print("=" * 70)
    print()

    plots_dir = Path("results_with_plots/plots")

    if not plots_dir.exists():
        print("No plots directory found. Run with --plots flag first:")
        print("  sangerqc all seq_data/Y19/ -o results_with_plots --recursive --plots")
        return

    plots = list(plots_dir.glob("*.png"))

    print(f"Found {len(plots)} plots in {plots_dir}/\n")

    descriptions = {
        "Y19_ITS4_trim.png": """
Individual Sequence Quality Plot
--------------------------------
Shows the quality profile for a single sequence with:
- Black line: Quality scores across the sequence
- Green shaded region: Kept (trimmed) portion
- Red shaded regions: Discarded portions (5' and 3' ends)
- Blue dashed line: Quality threshold used for trimming
- Gray dotted lines: Q20 and Q30 reference lines
- Text box: Summary statistics (lengths, trim coordinates, mean quality)

This visualizes exactly where the sequence was trimmed and why.
        """,

        "sequences_overview.png": """
Multi-Sequence Overview
-----------------------
Grid layout showing multiple sequences at once:
- Each subplot shows one sequence's quality profile
- Green regions: Kept sequences
- Red regions: Discarded sequences
- Blue line: Quality threshold
- Title shows sample ID and kept length

Useful for comparing trimming across multiple samples quickly.
        """,

        "summary_histograms.png": """
QC Metrics Summary Histograms
-----------------------------
Six histograms showing distribution of key metrics:
1. Raw Sequence Length - original lengths before trimming
2. Trimmed Sequence Length - lengths after trimming
3. Mean Quality Distribution - average quality per read
4. Q20 Percentage - fraction of bases with Q≥20
5. GC Content Distribution - GC% across all reads
6. Expected Errors - predicted error count per read

Useful for understanding overall dataset quality characteristics.
        """,

        "length_comparison.png": """
Length Comparison: Before vs After
----------------------------------
Two plots comparing raw and trimmed lengths:

Left panel (Bar Chart):
- Blue bars: Raw sequence lengths
- Green bars: Trimmed sequence lengths
- Shows per-sample comparison

Right panel (Scatter Plot):
- Each point represents one sequence
- X-axis: Raw length
- Y-axis: Trimmed length
- Red dashed line: No trimming (diagonal)
- Points below line indicate sequences were trimmed
- Text box: Overall retention statistics

Useful for assessing how much sequence was retained after trimming.
        """
    }

    for plot_path in sorted(plots):
        print(f"📊 {plot_path.name}")
        desc = descriptions.get(plot_path.name, "No description available")
        print(desc)
        print(f"   Location: {plot_path}")
        print(f"   Size: {plot_path.stat().st_size / 1024:.1f} KB")
        print()

    print("=" * 70)
    print("HOW TO VIEW THE PLOTS")
    print("=" * 70)
    print()
    print("Option 1: Copy to your local machine")
    print(f"  scp -r {plots_dir} your_local_machine:/path/to/destination/")
    print()
    print("Option 2: Use a file browser")
    print(f"  Navigate to: {plots_dir.absolute()}")
    print()
    print("Option 3: View in Jupyter")
    print("  from IPython.display import Image, display")
    print(f"  display(Image('{plots_dir}/Y19_ITS4_trim.png'))")
    print()
    print("=" * 70)

if __name__ == "__main__":
    describe_plots()
